name: theja
description: Let's sleep a little more
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  equatable: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.1
  flutter_slidable: ^0.5.4
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
  path: ^1.6.4
  http: ^0.12.2
  xml: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ 